---
title: "2nd Proposal"
author: "Siobhan Oberg"
date: "6/16/2021"
output: html_document
---
Can machine learning help us identify the current abundance of one of Oregon’s most significant trees to the cultural and natural history of the Willamette Valley?  The Willamette Valley is the traditional home of the Kalapuya people and the local oak has been important in sustaining them since time immemorial.  Today that oak is called the Oregon Oak, Oregon White Oak, Garry Oak, or Quercus garryana.  The Oregon Oak thrived across the Willamette Valley in a landscape that was managed by the Kalapuya using fire to keep the valley floor in an open savannah habitat.  With the arrival of European settlers, the traditional ecological patterns were broken as the fire was suppressed and savannah were converted into European agricultural practices. Since 1850, 97% of the native Oregon Oaks have disappeared with the large wide-reaching branches of the savannah form of the Oregon Oak becoming the rarest.  Although the productive open land that originally drew people to the Willamette Valley is vanishing, many landowners have retained the legacy trees of the trees that were signatures of the landscape managed by the Kalapuya. This project proposes using a combination of historical data about colonial-settler land use, current municipal data about street trees, and data from others interested in the conservation of Oregon Oaks to develop a machine learning program to identity all of the undocumented legacy oaks in the Willamette Valley.   The benefits of this new tool will be useful for government and nonprofit managers of biodiversity that is dependent on Oregon Oaks. The project will also be valuable for everyone that has a cultural connection to Oregon Oaks and the history of the Willamette Valley.    

Although the Oregon Oak plays a vital role in the landscape, culture and history of the Willamette Valley there are no general legal protections for the trees. The environmental role of the oaks alone should be enough to enact legal measures of protection for the trees. They serve as the primary habitats for sensitive species such as the slender-billed white-breasted nuthatch, as well as preventing soil erosion and filtrating water. 

Furthermore, the soil surrounding these oaks is prime agricultural land for wineries. The Oregon oaks in the fields of wineries are used as marketing devices. The trees appear in labels and logos of Willamette Valley wineries, making them a prominent facet of the culture in the Willamette Valley. 

The people and the animals that appreciate today’s large old oaks owe all some of the benefits to the Kalapuya people who managed the ecosystem that produced the generation of trees we admire today. The Kalapuyans cultivated the land of the Willamette Valley and cared for the Oregon white oaks for many years. Now, the trees are facing rapidly declining numbers, as well as the wildlife they host.




Using data collected by the City of Salem and Willamette University, I hope to develop a machine learning model that can distinguish Oregon white oaks from other species of trees, as well as determine the oldest of the oaks.

Despite the important ecological, cultural, and historical role the trees play, there are no legal protections for the oaks. 98% or more of the remaining Oregon white oak population is found on private land, and though there are conservation efforts, they are voluntary. Proving the historical and cultural role of the trees, in combination with the vital ecological role, could help promote legislature to protect the oaks and their surrounding habitats.

I propose using the Oregon white oaks to map out the traditional land of the Kalapuya people. This would prove the historical significance of the trees, and in addition to their ecological significance, provide the grounds for formal legal protection. So could we use data science and trees to map out traditional Native American lands?

In order to carry out this project, I will be working with Professor David Craig of Willamette University and his undergraduate research team, as well as the City of Salem forestry department. Using LiDAR data from the City of Salem and surveys of Willamette Valley wineries being conducted by the undergraduate team, I plan on creating KNN and Naive Bayes models to classify the trees. The first outcome variable will be the species of the tree, and the second will be the general age of the tree. I plan on using the height of the tree, width of the tree, density and color of leaves, and other features to determine species and age.

I hope to find old Oregon white oaks to help construct a map of the areas that the Kalapuya people inhabited before being pushed out of their lands by settlers. This would lend historical significance to the old trees and place them in a protected class.

The Oregon white oaks that have been a hallmark of Willamette Valley wineries are rapidly disappearing and there are no legal protections for the trees. As the Oregon white oaks disappear, so do hints into the past. Since the Kalapuya people carefully cultivated the land of the Willamette Valley, the survival of the native species is owed to them. The locations of older oaks could provide clues to more precise locations of the traditional Kalapuya lands.

If this project is successful, then similar programs could be initiated to map other traditional Native American lands. Using the locations of flora known to be cultivated by specific tribes, accurate maps of their traditional land could be created. Additionally, LiDAR data and machine learning classifications could be used to determine species of trees, as well as their health. This would allow for forestry departments to quickly identify areas that might need more biodiversity or more support to improve the health of the trees in a specific area.

Due to the fact that over 97% of native Oregon white oaks are no longer around, mapping the Kalapuya traditional lands could prove to be difficult. There is the very real possibility that there may not be enough Oregon white oaks left to provide an accurate map. Though unfortunate, that helps the argument that the trees need to be preserved. Future directions for the project would be perhaps to measure the impact of the loss of Oregon white oaks on the slender-billed, white-breasted nuthatch population in Oregon. The oaks are one of the primary habitats for the birds but they do live in other species of trees when the oaks are present. Perhaps there is a ratio of Oregon white oak to other tree species that the birds prefer. We could use data from eBird to map the populations of the nuthatches and then overlay that with maps of the Oregon white oaks. This project could also lay the groundwork for determining a relationship between urban tree canopy cover and discriminatory housing policies in Salem.
